### ISSUE TITLE
Not working: All `Compose for *` links on page https://console.bluemix.net/docs/services/ComposeEnterprise/index.html#about-compose-enterprise 

### ISSUE THREAD

**Issue by synergit** [ibm-cloud-docs/ComposeEnterprise#2]

**Comment by DailyAlice** [comment]
I think this has been fixed in the interim, probably due to the domain name change from `bluemix.net` to `cloud.ibm.com`.

The new URL for the page is https://cloud.ibm.com/docs/services/ComposeEnterprise?topic=compose-enterprise-about
and the links should all be live again.

Thanks!
